# This is a basic workflow to help you get started with Actions

name: docs-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ 08-04-2021-prueba ]
  pull_request:
    branches: [ 08-04-2021-prueba ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install sphinx_rtd_theme"
        docs-folder: "src/"
        build-command: "sphinx-build -b html . _build/html"
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentaciónHTML
        path: src/_build/html/
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make latexpdf"
        docs-folder: "src/"
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentaciónPDF
        path: src/_build/html/latex/erpya.pdf
    - uses: idlefingers/do-space-sync-action@master
      with:
        args: --acl public-read
      env:
        SOURCE_DIR: 'src/_build/html/latex/erpya.pdf'
        SPACE_NAME: ${{ secrets.SPACE_NAME }}
        SPACE_REGION: ${{ secrets.SPACE_REGION}}
        SPACE_ACCESS_KEY_ID: ${{ secrets.SPACE_ACCESS_KEY_ID }}
        SPACE_SECRET_ACCESS_KEY: ${{ secrets.SPACE_SECRET_ACCESS_KEY }}
        endpoint: 'https://.digitaloceanspaces.com'
    - name: Commit documentation changes
      run: |
        git clone https://github.com/TaniaLucena/docs.git --branch gh-pages --single-branch gh-pages
        cp -r src/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
